export const CREATE_CHAT_REQUEST = 'CREATE_CHAT_REQUEST'
export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT_SUCCESS'
export const CREATE_CHAT_FAIL = 'CREATE_CHAT_FAIL'


export const FETCH_ALL_CHATS_REQUEST = 'FETCH_ALL_CHATS_REQUEST'
export const FETCH_ALL_CHATS_SUCCESS = 'FETCH_ALL_CHATS_SUCCESS'
export const FETCH_ALL_CHATS_FAIL = 'FETCH_ALL_CHATS_FAIL'