export const GET_ALL_POST_REQUEST ='GET_ALL_POST_REQUEST'
export const GET_ALL_POST_SUCCESS ='GET_ALL_POST_SUCCESS'
export const GET_ALL_POST_FAIL ='GET_ALL_POST_FAIL'

export const ADD_NEW_POST_REQUEST ='ADD_NEW_POST_REQUEST'
export const ADD_NEW_POST_SUCCESS ='ADD_NEW_POST_SUCCESS'
export const ADD_NEW_POST_FAIL ='ADD_NEW_POST_FAIL'

export const LIKE_POST_REQUEST ='LIKE_POST_REQUEST'
export const LIKE_POST_SUCCESS ='LIKE_POST_SUCCESS'
export const LIKE_POST_FAIL ='LIKE_POST_FAIL'

export const COMMENT_POST_REQUEST ='COMMENT_POST_REQUEST'
export const COMMENT_POST_SUCCESS ='COMMENT_POST_SUCCESS'
export const COMMENT_POST_FAIL ='COMMENT_POST_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'