export const LOGIN_USER_REQUEST='LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS='LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL='LOGIN_USER_FAIL'

export const REGISTER_USER_REQUEST='REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS='REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL='REGISTER_USER_FAIL'

export const LOAD_USER_REQUEST='LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS='LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL='LOAD_USER_FAIL'

export const GET_USER_PROFILE_REQUEST='GET_USER_PROFILE_REQUEST'
export const GET_USER_PROFILE_SUCCESS='GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_FAIL='GET_USER_PROFILE_FAIL'

export const EDIT_USER_PROFILE_REQUEST='EDIT_USER_PROFILE_REQUEST'
export const EDIT_USER_PROFILE_SUCCESS='EDIT_USER_PROFILE_SUCCESS'
export const EDIT_USER_PROFILE_FAIL='EDIT_USER_PROFILE_FAIL'

export const SEARCH_USER_PROFILE_REQUEST='SEARCH_USER_PROFILE_REQUEST'
export const SEARCH_USER_PROFILE_SUCCESS='SEARCH_USER_PROFILE_SUCCESS'
export const SEARCH_USER_PROFILE_FAIL='SEARCH_USER_PROFILE_FAIL'

export const FOLLOW_USER_REQUEST='FOLLOW_USER_REQUEST'
export const FOLLOW_USER_SUCCESS='FOLLOW_USER_SUCCESS'
export const FOLLOW_USER_FAIL='FOLLOW_USER_FAIL' 

export const LOGOUT_USER_REQUEST='LOGOUT_USER_REQUEST'
export const LOGOUT_USER_SUCCESS='LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_FAIL='LOGOUT_USER_FAIL'

export const CHANGE_PASSWORD_REQUEST='CHANGE_PASSWORD_REQUEST'
export const CHANGE_PASSWORD_SUCCESS='CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL='CHANGE_PASSWORD_FAIL'

export const UPDATE_AVATAR_REQUEST = 'UPDATE_AVATAR_REQUEST'
export const UPDATE_AVATAR_SUCCESS='UPDATE_AVATAR_SUCCESS'
export const UPDATE_AVATAR_FAIL='UPDATE_AVATAR_FAIL'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS='DELETE_USER_SUCCESS'
export const DELETE_USER_FAIL='DELETE_USER_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'